version: "3.7"

services:
  nuxt-app:
    build:
      context: .
      no_cache: true
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - decent
networks:
  decent:
    name: decent
    external: true

